[package]
name = "barsstat"
version = "0.0.1"
authors = [ "Max Parmer <maxp@trystero.is>" ]
build = "build.rs"

[build-dependencies.gcc]
git = "https://github.com/alexcrichton/gcc-rs"

[[bin]]
name = "barsstat"
